### ISSUE TITLE
Filter Block devices on the basis of labels for a deployment

### ISSUE THREAD

**Issue by dunefro** [mayadata-io/cstorpoolauto#53]
Simple scenario! I want to deploy Elasticsearch and i need to provision some volumes. Now i have the blockdevices ( say 5) and I need to create a storage pool claim that should use (let's say) 2 of the blockdevices. Now for doing so I need to manually look at the blockdevices to be included and add them in the blockdeviceslist. The simple case can be, if the ndm or ndm operator(just saying) through some means is able to put a label on the blockdevice which will match the labels provided in the storage pool claim for es. If both of them match, we need not to mention the block device list in the storage pool claim.

**Comment by AmitKumarDas** [comment]
@dunefro CStorPoolAuto tries to abstract away BlockDevices, SPC & few others. It provides a new CR called `CStorClusterConfig` that deals with nodes, pool counts, raid type & csi drivers that support attach & detach. Will this information CStorPoolAuto operator should handle all the operations related to finding BlockDevices, creating CStorPool & so on.

Below is a sample file that does all the above:
```yaml
apiVersion: dao.mayadata.io/v1alpha1
kind: CStorClusterConfig
metadata:
    name: my-cstor-cluster
    namespace: openebs
spec:
    diskConfig:
        externalProvisioner:
            csiAttacherName: pd.csi.storage.gke.io
            storageClassName: csi-gce-pd
    poolConfig:
        raidType: mirror
```
