### ISSUE TITLE
bug: filter blockdevices that do not have any filesystem on them

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/cstorpoolauto#61]
Following is an example of BlockDevice that is fit to be considered to participate in building a CStor Pool.

```yaml
  spec:
    capacity:
      logicalSectorSize: 512
      physicalSectorSize: 0
      storage: 107374182400
    details:
      compliance: ""
      deviceType: ""
      firmwareRevision: ""
      model: PersistentDisk
      serial: pvc-c1919d99-3295-11ea-a90b-42010a800016
      vendor: Google
    devlinks:
    - kind: by-id
      links:
      - /dev/disk/by-id/scsi-0Google_PersistentDisk_pvc-c1919d99-3295-11ea-a90b-42010a800016
      - /dev/disk/by-id/google-pvc-c1919d99-3295-11ea-a90b-42010a800016
    - kind: by-path
      links:
      - /dev/disk/by-path/virtio-pci-0000:00:03.0-scsi-0:0:30:0
    filesystem: {}
    nodeAttributes:
      nodeName: gke-amitd-dao-d-default-pool-fcc50975-fvsb
    partitioned: "No"
    path: /dev/sde
  status:
    claimState: Unclaimed
    state: Active
```
