### ISSUE TITLE
bug: max pool count is not set

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/cstorpoolauto#75]
Max pool count field is always observed to be 0 as show below:
```yaml
  spec:
    diskConfig:
      externalProvisioner:
        csiAttacherName: pd.csi.storage.gke.io
        storageClassName: csi-gce-pd
      minCapacity: 107374182400
      minCount: 2
    maxPoolCount: 0
    minPoolCount: 3
    poolConfig:
      raidType: mirror
```
